### PR TITLE
ValueListBox implements HasName

### PR DESCRIPTION
**Pull request by slugmandrew**
I had a need for this so I forked and added it. The name needs to be set if the form is uploading to a servlet.

### CODE REVIEW

**Comment by jgodi** [comment]
Please update and conform the the style guide: https://travis-ci.org/gwtbootstrap3/gwtbootstrap3/jobs/49318200. Thanks!

**Comment by jgodi** [comment]
https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/CONTRIBUTING.md

**Comment by slugmandrew** [comment]
Ah, whoops! I did try to conform but didn't realise the tabs/spaces problem. Will sort it today.

**Comment by jgodi** [comment]
Thank you for fixing the issues and the PR. Good work.

**Pull request merged**
