### PR TITLE
Call setMultipleSelect() instead of deprecated super constructor

### PR DESCRIPTION
**Pull request by ArloL**

### CODE REVIEW

**Comment by crevete** [comment]
This would be better, to avoid duplicated code :

```
public ListBox(final boolean isMultipleSelect) {
    this();
    setMultipleSelect(isMultipleSelect);
}
```

**Comment by ArloL** [comment]
Good idea!

**Comment by ArloL** [comment]
Maybe we should deprecate the constructor as well?

**Comment by jgodi** [comment]
Nice job!

**Pull request merged**
