### PR TITLE
setIconColor in HasIcon interface

### PR DESCRIPTION
**Pull request by caesaralves**
Added the `void setIconColor(String iconColor);` method to `HasIcon` Interface.

### CODE REVIEW

**Comment by caesaralves** [comment]
Travis is giving me weird errors, I didn't touch the files that he's complaining about ;)

**Comment by sjardine** [comment]
Please fix checkstyle errors.  It looks like you are using tab characters instead of spaces.

**Comment by sjardine** [comment]
There are a few more issues relating to style and documentation.  Please check the travis-ci build for more information.

**Comment by caesaralves** [comment]
Hey @sjardine dunno what the problem is. It's complaining about headers "There are 8 file(s) with header to update:". What is this about? Thanks
Cheers

**Comment by caesaralves** [comment]
Why travis was failing?

**Comment by sjardine** [comment]
It was looking for a specific header.

**Pull request merged**
