### PR TITLE
add getter/setter for HTML content

### PR DESCRIPTION
**Pull request by bauna**
I need this getter / setter display html on ListGroup

### CODE REVIEW

**Comment by crevete** [comment]
Great, thanks for your PR.

**Comment by crevete** [comment]
@bauna My bad, I'm sorry but I've got a problem with this PR...
In fact, the ```ListGroupItem``` is a ```ComplexWidget```, it cannot implement ```HasText``` or ```HasHTML``` interfaces. Since this will broke when using on uiBinder (cf. our demo page)

**Comment by bauna** [comment]
And how we add bold text a ListGroupItem that's only what I need.

Can we leave the method but not implement HasHTML?

**Comment by crevete** [comment]
I have left the ```setHtml()``` method and just removed ```implement HasHTML``` interface.

In fact, you can just create a ```Strong text = new Strong()```, and add it to the ListGroupItem.

**Pull request merged**
