### PR TITLE
Added support for icons in Modal and ModalHeader

### PR DESCRIPTION
**Pull request by sjardine**
Modal now has a titleIcon property which accepts an IconType.

### CODE REVIEW

**Comment by crevete** [comment]
I'am sorry, but your implementation is totally wrong... The method you've added is ```setIconTitle()```, but it acts as ```addIconTitle()```. In fact, if you call it N times, the icon will also be added N times.

**Comment by jgodi** [comment]
Why not just do as the ```Heading``` widget and add an ```icon``` then add/remove it if it is set?

**Comment by ArloL** [comment]
@sjardine Thanks for taking the time to create a PR. Am I understanding you correctly that you want to type

~~~
<b:Modal title="Cupcake ipsum" titleIcon="SEARCH">
</b:Modal>
~~~

instead of

~~~
<b:Modal>
  <b:ModalHeader>
    <b:Heading size="H4">
      <b:Icon type="SEARCH"/>
      <b:Text text="Cupcake ipsum"/>
    </b:Heading>
  </b:ModalHeader>
</b:Modal>
~~~

Do you believe that this is a convenience we *have* to add to the library? Because IMO this is an edge case. Please convince me (us) if otherwise!

As a sidenote this does not implement HasIconPosition. So you can't place the icon on the right.

It's also not possible to implement

~~~
<b:Heading size="H4">
    <b:Text text="Cupcake "/>
    <b:Icon type="SEARCH"/>
    <b:Text text=" ipsum"/>
</b:Heading>
~~~

Another sidenote: This is a case where the discussion in #281 really fits. It's just way easier and more flexible to do this with vanilla HTML instead of using Widgets:

~~~
<g:HTMLPanel>
<div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Cupcake <span class="glyphicon glyphicon-search" aria-hidden="true"></span> ipsum</h4>
      </div>
    </div>
  </div>
</div>
</g:HTMLPanel>
~~~

**Comment by jgodi** [comment]
I agree with @ArloL, this is an edge case and there are means within the library to achieve this.

**Comment by sjardine** [comment]
Thanks @ArloL.  I appreciate you taking the time to explain this in detail.

**Comment by ArloL** [comment]
No worries. Please don't let this discourage you to make PRs in the future!

**Pull request closed without merging**
