### PR TITLE
Fixed a few java warning messages

### PR DESCRIPTION
**Pull request by sjardine**
Fixed a few warning messages. 

1.  Added a header comment.
2.  Added 2 default case statements
3.  Removed unnecessary @SuppressWarnings("unused") annotation.

### CODE REVIEW

**Comment by ArloL** [comment]
Shouldn't #230 have caught https://github.com/sjardine/gwtbootstrap3/commit/dd4b8e694d81fd4a41b664d3036a2ebb1bc2e277?

Rest looks good to me.

**Comment by jgodi** [comment]
Yes, it should have. Let me double check and test it out later today. Good catch.

**Comment by jgodi** [comment]
I am going to look into better CI and even deployment for this library so that everything can be as seemless as possible. Right now, deploying a demo and api docs is tedious!

**Comment by ArloL** [comment]
We should look into using travis CI.

https://github.com/rgladwell/m2e-android has a great example of how they do their site deploys. The interesting parts are https://github.com/rgladwell/m2e-android/blob/master/me.gladwell.eclipse.m2e.android.update/pom.xml#L51 and https://github.com/rgladwell/m2e-android/blob/master/.travis.yml#L52

**Pull request merged**
