### PR TITLE
Added required star to FormLabel.

### PR DESCRIPTION
**Pull request by sjardine**
I think this is a good feature but will understand if it is not wanted.  When the "required" field is specified in uibinder then a star icon is displayed following the label.

I like the way the icon is added better than the HelpBlock implementation but it is a more complicated implementation.

Here is a screenshot:
requiredstar

Let me know what you think.

### CODE REVIEW

**Comment by jgodi** [comment]
Can you make it optional? It might not be in some people's UI/UX to have that, maybe give a way to opt out?

**Comment by sjardine** [comment]
Yeah...its optional in the fact that if you don't include "required" in uibinder then it defaults to not required. Is that what you meant?

**Comment by jgodi** [comment]
Oh I meant as an additional flag like "showRequiredIndicator". Some might want to have the required flag for validation but not show the asterix.

**Comment by sjardine** [comment]
Oh.  No worries there.  It applies only to the FormLabel and is 
independent of validation.  You could have a star and no validation if 
you wanted or no star and validation. Should be very flexible.

On 02/12/2015 05:44 PM, Joshua Godi wrote:
>
> Oh I meant as an additional flag like "showRequiredIndicator". Some 
> might want to have the required flag for validation but not show the 
> asterix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gwtbootstrap3/gwtbootstrap3/pull/312#issuecomment-74184930>.
>



IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms.

**Comment by sjardine** [comment]
I think I will change the name to showRequiredIndicator like you said to avoid confusion.

On February 12, 2015 5:44:39 PM MST, Joshua Godi <notifications@github.com> wrote:
>Oh I meant as an additional flag like "showRequiredIndicator". Some
>might want to have the required flag for validation but not show the
>asterix. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gwtbootstrap3/gwtbootstrap3/pull/312#issuecomment-74184930

-- 
Sent from Kaiten Mail. Please excuse my brevity.

IMPORTANT: This email does not constitute a contract or an offer or acceptance of an offer to enter into a contract.  Further, this email may not be used to modify, supplement, novate, or waive any rights with respect to an existing contract or other binding commercial terms.

**Comment by sjardine** [comment]
Should be good to go.

**Pull request merged**
