### PR TITLE
Implemented Badges for Buttons, Tabs, Navs - closes #351

### LINKED ISSUE #351: Allow TabListItem to accept widgets instead of just text
I was wondering how people would feel about allowing `TabListItem` to accept children such as `Icon` and `Badge`?

This would be a good feature for the library IMO and I believe vanilla bootstrap allows this. I'm guessing we would have to make `TabListItem` implement `HasWidgets` and `HasIcon`. Currently it implements `HasText` so I get this error:

> Illegal child <b:Badge> in a text-only context. Perhaps you are trying to use unescaped HTML where text is required, as in a HasText widget?: <b:TabListItem active='true' dataTarget='#info' ui:field='infoTab'>

Code:
```xml
<b:TabListItem ui:field="infoTab" dataTarget="#info" active="true" icon="PLUS">
    Info
    <b:Badge>0</b:Badge>
</b:TabListItem>
```

http://getbootstrap.com/components/#badges

What do people think? I'm happy to try and implement it, but thought I'd ask for some feedback as I obviously want to do it in keeping with the design decisions of the library.

### PR DESCRIPTION
**Pull request by slugmandrew**
After much messing around I think this is just about ready. New interface `HasBadge` which allows a text and position of the badge to be set.

A few points:
**Breaking change** : Tabs must now be initialised in UiBinder like this: `<b:TabListItem text="Tab 1"/>` instead of `<b:TabListItem>Tab 1</b:TabListItem>`.

The functionality has been added into `IconTextMixin` as this was the best way I could find to perform the rendering (Could be renamed IconTextBadgeMixin? - I toyed with an additional BadgeMixin but it didn't seem the right approach).

The syntax is pretty straightforward, and badges default to the right hand side:

    <b:AnchorListItem icon="ANDROID" badgeText="42">Item 2</b:AnchorListItem>`
    <b:AnchorListItem icon="ANDROID" iconPosition="RIGHT" badgeText="42" badgePosition="LEFT">Item 3</b:AnchorListItem>`

Some dummy screens (I haven't finished updating the demo on my side yet, but will do if this gets ok'd):

image

image

image

Let me know your thoughts! Hopefully it's a useful addition to an already great library. And sorry again for this taking so long :/

### CODE REVIEW

**Comment by crevete** [comment]
That looks great! Thanks for your work!
The only question is : why you have to drop the support for ```<b:TabListItem>Tab 1</b:TabListItem>``` ? Is it possible to keep this syntax in UiBinder?

**Comment by sjardine** [comment]
+1 to question by @crevete

**Comment by slugmandrew** [comment]
Ah! Good question, and of course you are right... We don't! I think along the way I got confused and thought I needed a `@UiConstructor` annotated constructor somewhere. No matter, I'll fix that and commit the fix again.

One last question regarding the demo - Where would be best to add some examples? I don't want to clutter the pages for the Navs, Tabs and Buttons too much as I think for a beginner learning it's good to just have the basics there. Should I just add a few more examples to the Badges page instead? I think that would be the best solution.

**Comment by sjardine** [comment]
Thanks!

**Pull request merged**
