### PR TITLE
Testing Travis-CI

### PR DESCRIPTION
**Pull request by jgodi**
Don't close this, just testing things out!

### CODE REVIEW

**Comment by jgodi** [comment]
@ArloL, doesn't seem that the build fails with no license headers.

**Comment by jgodi** [comment]
Need to configure travis to deploy snapshots, and install the gwtbootstrap3/gwtbootstrap3-extras so that the demo/extras can build without pulling from sonatype.

**Comment by jgodi** [comment]
Ok, I have all three repositories building with Travis CI and succeeding. The only thing that I have to do is deploy new snapshots for gwtbootstrap3 and gwtbootstrap3-extras for them to succeed.

Still want to tweek some things:

- [ ] make builds fail without license headers
- [ ] configure travis ci to deploy snapshots for gwtbootstrap3 and gwtbootstrap3-extras
- [ ] configure travis ci to deploy gwtbootstrap3-demo to the gh-pages branch under snapshot
- [ ] configure travis ci to deploy gwtbootstrap3 apidocs to the gh-pages branch under snapshot/apidocs

I don't know exactly how to do these yet, but if you guys had any suggestions or ideas that would be great! Thanks!

**Comment by ArloL** [comment]
Maybe add check-file-header to https://github.com/gwtbootstrap3/gwtbootstrap3/blob/master/pom.xml#L91

**Comment by ArloL** [comment]
I know what the problem is. Travis CI by default will call `mvn install -DskipTests=true` before running our script. That steps adds the missing headers (dryRun=false). See http://docs.travis-ci.com/user/languages/java/ for details.

I will try changing that step.

**Comment by ArloL** [comment]
#291 does the trick.

**Comment by jgodi** [comment]
Nice, thanks! I will look into the others tomorrow and hopefully get those going!

**Pull request closed without merging**
