### PR TITLE
Adds ButtonCell class

### LINKED ISSUE #240: Add ButtonCell
Hi,

It would be really useful to have a ButtonCell with a Button inside.

I will try to implement one, and if satisfied, I will make a PR.

### PR DESCRIPTION
**Pull request by rsertelon**
Fixes #240.

Hope this is what was expected :)

### CODE REVIEW

**Comment by jgodi** [comment]
Awesome, thanks. Would you have time to add an example into the demo?

**Comment by jgodi** [comment]
Also, what about enabling/disabling the button? I think that is the only missing major state for the button.

**Comment by rsertelon** [comment]
How would you disable the button? In the constructor too?

As for the example in demo, I really can't promise anything. It seems not to be as trivial as a simple button as it has to be used in a CellTable.

**Comment by ArloL** [comment]
I think jgodi is talking of a setEnabled(true/false) that will then enable/disable the button.

**Comment by jgodi** [comment]
Yes, and as for the demo I can add it into the demo over the next few days. Thanks!

**Comment by rsertelon** [comment]
Hmm I don't know how this setEnabled method will be called.

Indeed, AFAIK, we use the ButtonCell as an argument to the Column constructor: `super(new ButtonCell(...))`. Do you know any case where we use this class otherwise?

**Comment by jgodi** [comment]
This is a good start. I would like it to be more robust and be able to change things on it on the fly like icon/type/enable state/etc. But that would be an enhancement as needed.

**Comment by rsertelon** [comment]
I understand. What could be do then to consider this PR complete?

**Comment by jgodi** [comment]
I think this is good for now. I will write up a new issue that can be resolved in 1.0. Thanks!

**Comment by jgodi** [comment]
Works perfectly, thanks. https://github.com/gwtbootstrap3/gwtbootstrap3-demo/commit/593b38841a6b613bc39a283ec088353105e0048e

**Comment by rsertelon** [comment]
You're welcome :)

**Pull request merged**
