### PR TITLE
Demonstrating Travis deployment of snapshots

### PR DESCRIPTION
**Pull request by ArloL**
It obviously doesn't work yet because I don't have the credentials. This is the call that created the secret environment variables
~~~~
travis encrypt -r gwtbootstrap3/gwtbootstrap3 OSSRH_USER=test
travis encrypt -r gwtbootstrap3/gwtbootstrap3 OSSRH_PASS=test
~~~~

If the correct credentials are in there it should work.

Disclaimer: This is my first time using Travis CI for deployment so it might not work 100% ;)

Sources:
http://notbarjo.blogspot.de/2014/09/travis-ci-maven-deploy.html
http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
http://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps
https://coderwall.com/p/9b_lfq/deploying-maven-artifacts-from-travis
http://docs.travis-ci.com/user/encryption-keys/

### CODE REVIEW

**Comment by jgodi** [comment]
@ArloL This is 100% safe? :P

**Comment by ArloL** [comment]
Safe in regards with the password?

Well it is encrypted using the public/private key combination that Travis CI created for gwtbootstrap3/gwtbootstrap3. So only Travis CI can decrypt it. Unless of course the encryption is broken (don't know exactly what they're using) which is unlikely.

**Comment by jgodi** [comment]
Thanks for looking into this. I will set this up now and test it out!

**Comment by jgodi** [comment]
Looks like it will work, just getting Service Temporarily Unavailable for now. Go figure :P

**Comment by ArloL** [comment]
You should be able to restart the build: http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by jgodi** [comment]
Hmm, seems to work locally just fine but on travis ci it still gives that error. I will have to mess around with it later. Thanks for the help!

**Comment by ArloL** [comment]
Hmm :/

**Comment by jgodi** [comment]
I am getting this error for the extras/demo now: 

``` Non-resolvable parent POM: Could not transfer artifact org.gwtbootstrap3:gwtbootstrap3-parent:pom:0.9-SNAPSHOT from/to sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/gwtbootstrap3/gwtbootstrap3-parent/0.9-SNAPSHOT/gwtbootstrap3-parent-0.9-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable. and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]```

Not quite sure. But I did figure out how to input the user/pass via the Travis CI settings. Still those errors though >.<

**Pull request merged**
